# Required to set the distro to Ubuntu Trusty (14.04)
# https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
sudo: required
dist: trusty

language: python

python:
 - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential git cmake qt5-default qtbase5-dev libxml2-dev libxslt-dev qttools5-dev-tools libqt5clucene5 libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5 libqt5designercomponents5 libqt5feedback5 libqt5gui5 libqt5help5 libqt5multimedia5 libqt5network5 libqt5opengl5 libqt5opengl5-dev libqt5organizer5 libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5quick5 libqt5script5 libqt5scripttools5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webkit5 libqt5widgets5 libqt5xml5 libqt5xmlpatterns5 libqt5xmlpatterns5-dev

install:
  # This just prints the Qt version info to the console
  - qmake -query

  - mkdir build && cd build
  - cmake ..
  - make

script:
  # The "ARGS" makes CTest show verbose test output.
  - make test ARGS="-V"