# Required to set the distro to Ubuntu Trusty (14.04)
# https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
sudo: required
dist: trusty

language: python

python:
 - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential git cmake qt5-default libxml2-dev libxslt-dev qttools5-dev-tools libqt5test5 libqt5xml5 libqt5xmlpatterns5 libqt5xmlpatterns5-dev 

install:
  - mkdir build && cd build
  - cmake ..
  - make -j4

script:
  # The "ARGS" makes CTest show verbose test output.
  - make test ARGS="-V"