# Required to set the distro to Ubuntu Trusty (14.04)
# https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
sudo: required
dist: trusty

language: python

python:
 - "2.7"

before_install:
  # This adds Qt5.5.1 - the default version that comes with Trusty is 5.2
  # You can see the package list here:
  # https://launchpad.net/~beineri/+archive/ubuntu/opt-qt551-trusty
  - sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty

  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential git cmake qt55-base libxml2-dev libxslt-dev qt55tools qt55xmlpatterns5

  - source /opt/qt55/bin/qt55-env.sh

install:
  # This just prints the Qt version info to the console
  - qmake -query

  - mkdir build && cd build
  - cmake ..
  - make

script:
  # The "ARGS" makes CTest show verbose test output.
  - make test ARGS="-V"